image: node:latest

services:
  - postgres:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - ssh-copy-id -i $SERVER_SSH_KEY $SERVER_ADMIN@$SERVER_URL
    - rsync -avuz $CI_PROJECT_DIR/server/ $SERVER_ADMIN@$SERVER_URL:/var/wwww/api.weshareashare
  environment:
    name: staging
    url: api.weshareashare.com
  only:
  - master

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
   
   
