image: node:8.8.1-alpine

variables:
  POSTGRES_DB: weshareashare
  POSTGRES_USER: weshareashare
  POSTGRES_PASSWORD: "123456"

cache:
  paths:
  - ./server/node_modules/
  - ./mobile/node_modules/
  - ./desktop/node_modules/

stages:
  - deploy

test_server:
  stage: test_server
  script:
    - echo "**Running Server tests**"
    - npm --prefix ./server install
    - echo "**Terminating Server tests**"

test_mobile:
  stage: test_mobile
  script:
    - echo "**Running Mobile tests**"
    - npm --prefix ./mobile install
    - echo "**Terminating Mobile tests**"

test_desktop:
  stage: test_desktop
  script:
    - echo "**Running Desktop tests**"
    - npm --prefix ./desktop install
    - echo "**Terminating Desktop tests**"

build:
  stage: build
  script:
    - echo "Building the app"

deploy:
  stage: deploy
  tags:
    - server
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
  only:
  - master
