image: node:8.8.1-alpine

variables:
  POSTGRES_DB: weshareashare
  POSTGRES_USER: weshareashare
  POSTGRES_PASSWORD: "123456"

cache:
  paths:
  - ./server/node_modules/
  - ./mobile/node_modules/
  - ./desktop/node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - server
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
  only:
  - master
