version: "3.3"

services:
  desktop:
    build: .
    ports:
         - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    external:
      name: server